"""Deterministic rule-based fallback used when the OpenAI Agents SDK / network
is unavailable. Guarantees the background job ALWAYS produces useful advice,
even fully offline.
"""
from __future__ import annotations

from typing import Any


def rule_based_financial_advice(summary: dict[str, Any]) -> str:
    total_sales = float(summary.get("total_sales", 0) or 0)
    total_expenses = float(summary.get("total_expenses", 0) or 0)
    net_profit = summary.get("net_profit")
    if net_profit is None:
        net_profit = round(total_sales - total_expenses, 2)

    lines = [
        f"Month summary: sales ${total_sales:,.2f}, expenses ${total_expenses:,.2f}, "
        f"net profit ${net_profit:,.2f}.",
    ]

    if total_sales == 0 and total_expenses == 0:
        lines.append("No transactions recorded yet this month — log a sale or expense to get tailored advice.")
    elif net_profit < 0:
        lines.append(
            "You are operating at a loss this month. Review your largest expense "
            "category first and consider deferring non-essential spending."
        )
    elif total_expenses > 0 and total_expenses / max(total_sales, 1) > 0.7:
        lines.append(
            "Expenses are consuming over 70% of sales revenue. Look for recurring "
            "costs that can be renegotiated or cut."
        )
    else:
        lines.append("Profit margin looks healthy this month. Consider setting aside a reserve for slow months.")

    lines.append("(Generated by rule-based fallback engine — AI advisor unavailable.)")
    return " ".join(lines)
